Update minimum golang version in readme to 1.18
The docker cli dep uses strings.Cut which was added in GO 1.18

../../go/pkg/mod/github.com/docker/cli@v24.0.5+incompatible/cli/config/credentials/file_store.go:79:20: undefined: strings.Cut